### ISSUE TITLE
Server Interceptor?

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalapb/zio-grpc#501]
It seems like there's no Server Interceptor? Is there a plan to do it?

**Comment by thesamet** [comment]
Hi @jxnu-liguobin , you can use [transformations](https://scalapb.github.io/zio-grpc/docs/next/decorating) to perform pretty much anything before or after the call. Can you check if it solves for your use case, and if not - let me know what you're trying to accomplish?

**Comment by jxnu-liguobin** [comment]
I am implementing a non-invasive opentrace plugin for [skywalking](https://github.com/apache/skywalking).
GRPC has its own server interceptor, just like a client interceptor. But currently, zio grpc only implements client interceptor `ZClientInterceptor`. 
Of course, zio grpc also can pass interceptors  it by builder, but due to rewriting `ZServerCallHandler`, it will not be truly used.

**Comment by jxnu-liguobin** [comment]
> > but due to rewriting ZServerCallHandler#startCall, it will not be truly used.
> 
> Were you able to test and confirm that? If this indeed doesn't work, we can add support, but I think it should work out of the box with the grpc-java interceptors.

It is possible to intercept by grpc-java, and I will confirm it tomorrow. But my expectation is to intercept ziogrpc directly. After a moment of thought, it seems that the server side is not necessary.

**Comment by jxnu-liguobin** [comment]
@thesamet You are right. I tried Skywalking's grpc-java agent. However, the request cannot be completed normally and will continue to block. Currently, I have not found the reason.

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin , does the same issue happen when using skywalking's agent with grpc-java directly and without zio-grpc? Please let me know if you need further assistance on this issue, and if so can you provide a minimal example to show the problem.

Thanks，and I will try again and create a minimum example when I have time

**Comment by jxnu-liguobin** [comment]
It has been confirmed that using only java grpc (not zio-grpc), the skywalking-java agent plugin can collect traces normally.
Such as:
<img width="647" alt="image" src="https://github.com/scalapb/zio-grpc/assets/29496873/a0d9d19e-7481-4536-a160-e6e8781185e2">


Here is my environment and  to reproduce it:

The following is the [smallest example](https://github.com/scalapb/zio-grpc/tree/master/examples/helloworld) that comes with zio-grpc to verify that the official skywalking-java grpc plugin does not work properly in zio-grpc.

1.The server received the request correctly 
![image](https://github.com/scalapb/zio-grpc/assets/29496873/a07dc3f9-c84d-44d2-b513-d19c49377aab)

2.But the client has no output, as mentioned above, I guess request was blocked or handler doesnot write response while processing the request at server side. 
![image](https://github.com/scalapb/zio-grpc/assets/29496873/9eb8203d-dfa3-485b-9d48-f6477d8f754f)

Run in IDEA:
![image](https://github.com/scalapb/zio-grpc/assets/29496873/19ab2c04-b7e5-416c-894b-6addd3d5e2d0)
![image](https://github.com/scalapb/zio-grpc/assets/29496873/ec71e5e4-42ba-484b-b3f9-5133e9646aa7)

Download the release package for skywalking-java without any unnecessary changes. `/Users/liguobin/Downloads/skywalking-agent/skywalking-agent.jar`


Run docker and deploy following docker-compose.yml: 
```
version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - "TAKE_FILE_OWNERSHIP=true"
      - "discovery.type=single-node"
      - "TZ=Asia/Shanghai"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  skywalking-oap-server:
    image: apache/skywalking-oap-server:8.9.1
    container_name: skywalking-oap-server
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      TZ: Asia/Shanghai
  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap-server:12800
      TZ: Asia/Shanghai
```
We can access trace in the browser: `http://localhost:8080/trace`
